version: '2.0'
services:
  springboot:
    build: .
    environment:
    - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/creativedrive_users
    container_name: creativedrive_users_api
    ports:
    - 8182:8080
    depends_on:
    - mongo
    links:
    - mongo
    networks:
    - spring-mongo-net
  mongo:
    image: mongo
    container_name: creativedrive_users_mongo
    ports:
    - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
    networks:
    - spring-mongo-net
networks:
  spring-mongo-net:
    driver: bridge